# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      parameter1:
        description:  "指定编译服务，默认编译所有服务[admin-api,admin-rpc,stat-rpc,admin-task @ hall-api,mq-record,mq-usercenter,rpc-act,rpc-usercenter,rpc-game,rpc-datacenter,task-record,task-dbcreator]"
        required: true
        default: "默认值1"
      parameter2:
        description: "输入参数2"
        required: true
        default: "默认值2"
      parameter3:
        description: "输入参数3"
        required: true
        default: "默认值3"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.0'

    - name: Install dependencies
      run: |
        go env -w GOPROXY=https://goproxy.cn,direct
        go mod download
    - name: Build
      run:  CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o hello main.go


#    - name: copy file via ssh password
#      uses: appleboy/scp-action@v0.1.7
#      with:
#        host: "13.202.241.120"
#        username: ubuntu
#        key: ${{secrets.BUILD_HOST_KEY}}
#        port: 22
#        source: "hello"
#        target: "/home/ubuntu/hy_platform/bin"
#
#
#
#    - name: file commands
#      uses: appleboy/ssh-action@v1.2.0
#      with:
#        host: "13.202.241.120"
#        username: ubuntu
#        key: ${{secrets.BUILD_HOST_KEY}}
#        port: 22
#        script_path: scripts/script.sh